Resources:
  CoffeinVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Coffein-Network

  CoffeinBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-coffein-bucket-${AWS::AccountId}

  CoffeinInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Coffein-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CoffeinVPC
      InternetGatewayId: !Ref CoffeinInternetGateway

  CoffeinPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CoffeinVPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Coffein-PublicSubnet-A

  CoffeinPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CoffeinVPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Coffein-PublicSubnet-B

  CoffeinRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Coffein-RouteTable