AWSTemplateFormatVersion: "TEST_AWS-git-2010-09-09"
Resources:
  CoffeinVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Coffein-Network

